#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/sony/pdx237

PRODUCT_COPY_FILES += \
    vendor/sony/pdx237/proprietary/odm/etc/customization/SO-53D/config.prop:$(TARGET_COPY_OUT_ODM)/etc/customization/SO-53D/config.prop \
    vendor/sony/pdx237/proprietary/odm/etc/customization/SOG12_jp_kdi/config.prop:$(TARGET_COPY_OUT_ODM)/etc/customization/SOG12_jp_kdi/config.prop \
    vendor/sony/pdx237/proprietary/odm/etc/customization/XQ-DE44/config.prop:$(TARGET_COPY_OUT_ODM)/etc/customization/XQ-DE44/config.prop \
    vendor/sony/pdx237/proprietary/odm/etc/customization/XQ-DE44_jp_rktn/config.prop:$(TARGET_COPY_OUT_ODM)/etc/customization/XQ-DE44_jp_rktn/config.prop \
    vendor/sony/pdx237/proprietary/odm/etc/customization/XQ-DE54_EEA/config.prop:$(TARGET_COPY_OUT_ODM)/etc/customization/XQ-DE54_EEA/config.prop \
    vendor/sony/pdx237/proprietary/odm/etc/customization/XQ-DE72/config.prop:$(TARGET_COPY_OUT_ODM)/etc/customization/XQ-DE72/config.prop \
    vendor/sony/pdx237/proprietary/odm/etc/customization/XQ-DE72_CN/config.prop:$(TARGET_COPY_OUT_ODM)/etc/customization/XQ-DE72_CN/config.prop \
    vendor/sony/pdx237/proprietary/odm/etc/customization/c000002/config.prop:$(TARGET_COPY_OUT_ODM)/etc/customization/c000002/config.prop \
    vendor/sony/pdx237/proprietary/odm/etc/customization/c000018/config.prop:$(TARGET_COPY_OUT_ODM)/etc/customization/c000018/config.prop \
    vendor/sony/pdx237/proprietary/odm/etc/customization/c000027/config.prop:$(TARGET_COPY_OUT_ODM)/etc/customization/c000027/config.prop \
    vendor/sony/pdx237/proprietary/odm/etc/customization/c000032/config.prop:$(TARGET_COPY_OUT_ODM)/etc/customization/c000032/config.prop \
    vendor/sony/pdx237/proprietary/odm/etc/customization/c001435/config.prop:$(TARGET_COPY_OUT_ODM)/etc/customization/c001435/config.prop \
    vendor/sony/pdx237/proprietary/odm/etc/customization/c001492/config.prop:$(TARGET_COPY_OUT_ODM)/etc/customization/c001492/config.prop \
    vendor/sony/pdx237/proprietary/odm/etc/customization/c001526/config.prop:$(TARGET_COPY_OUT_ODM)/etc/customization/c001526/config.prop \
    vendor/sony/pdx237/proprietary/odm/etc/customization/c001707/config.prop:$(TARGET_COPY_OUT_ODM)/etc/customization/c001707/config.prop \
    vendor/sony/pdx237/proprietary/odm/etc/customization/c001839/config.prop:$(TARGET_COPY_OUT_ODM)/etc/customization/c001839/config.prop \
    vendor/sony/pdx237/proprietary/odm/etc/customization/c001884/config.prop:$(TARGET_COPY_OUT_ODM)/etc/customization/c001884/config.prop \
    vendor/sony/pdx237/proprietary/odm/etc/customization/c999990/config.prop:$(TARGET_COPY_OUT_ODM)/etc/customization/c999990/config.prop \
    vendor/sony/pdx237/proprietary/odm/etc/customization/c999996/config.prop:$(TARGET_COPY_OUT_ODM)/etc/customization/c999996/config.prop \
    vendor/sony/pdx237/proprietary/odm/etc/customization/c999997/config.prop:$(TARGET_COPY_OUT_ODM)/etc/customization/c999997/config.prop \
    vendor/sony/pdx237/proprietary/odm/etc/customization/c999998/config.prop:$(TARGET_COPY_OUT_ODM)/etc/customization/c999998/config.prop \
    vendor/sony/pdx237/proprietary/odm/etc/customization/c999999/config.prop:$(TARGET_COPY_OUT_ODM)/etc/customization/c999999/config.prop \
    vendor/sony/pdx237/proprietary/vendor/camera/SEM52BC0/lens_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM52BC0/lens_ctrl.dat \
    vendor/sony/pdx237/proprietary/vendor/camera/SUN12BS1/color_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SUN12BS1/color_ctrl.dat \
    vendor/sony/pdx237/proprietary/vendor/camera/SUN12BS1/dataflow.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SUN12BS1/dataflow.dat \
    vendor/sony/pdx237/proprietary/vendor/camera/SUN12BS1/draw_comp_histogram.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SUN12BS1/draw_comp_histogram.dat \
    vendor/sony/pdx237/proprietary/vendor/camera/SUN12BS1/draw_comp_pocky.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SUN12BS1/draw_comp_pocky.dat \
    vendor/sony/pdx237/proprietary/vendor/camera/SUN12BS1/dual_bokeh_comp.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SUN12BS1/dual_bokeh_comp.dat \
    vendor/sony/pdx237/proprietary/vendor/camera/SUN12BS1/exposure_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SUN12BS1/exposure_ctrl.dat \
    vendor/sony/pdx237/proprietary/vendor/camera/SUN12BS1/exposure_ctrl_diagram.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SUN12BS1/exposure_ctrl_diagram.dat \
    vendor/sony/pdx237/proprietary/vendor/camera/SUN12BS1/eye_stabilizer.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SUN12BS1/eye_stabilizer.dat \
    vendor/sony/pdx237/proprietary/vendor/camera/SUN12BS1/face_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SUN12BS1/face_detector.dat \
    vendor/sony/pdx237/proprietary/vendor/camera/SUN12BS1/face_detector_soda.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SUN12BS1/face_detector_soda.dat \
    vendor/sony/pdx237/proprietary/vendor/camera/SUN12BS1/flicker_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SUN12BS1/flicker_detector.dat \
    vendor/sony/pdx237/proprietary/vendor/camera/SUN12BS1/food_comp_yummy.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SUN12BS1/food_comp_yummy.dat \
    vendor/sony/pdx237/proprietary/vendor/camera/SUN12BS1/hal_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SUN12BS1/hal_ctrl.dat \
    vendor/sony/pdx237/proprietary/vendor/camera/SUN12BS1/hal_ctrl_ife_lsc41.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SUN12BS1/hal_ctrl_ife_lsc41.dat \
    vendor/sony/pdx237/proprietary/vendor/camera/SUN12BS1/hdr_comp.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SUN12BS1/hdr_comp.dat \
    vendor/sony/pdx237/proprietary/vendor/camera/SUN12BS1/idt_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SUN12BS1/idt_ctrl.dat \
    vendor/sony/pdx237/proprietary/vendor/camera/SUN12BS1/image_conv.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SUN12BS1/image_conv.dat \
    vendor/sony/pdx237/proprietary/vendor/camera/SUN12BS1/image_conv_cheesescone.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SUN12BS1/image_conv_cheesescone.dat \
    vendor/sony/pdx237/proprietary/vendor/camera/SUN12BS1/image_conv_marble.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SUN12BS1/image_conv_marble.dat \
    vendor/sony/pdx237/proprietary/vendor/camera/SUN12BS1/image_conv_raisin.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SUN12BS1/image_conv_raisin.dat \
    vendor/sony/pdx237/proprietary/vendor/camera/SUN12BS1/image_conv_zunda.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SUN12BS1/image_conv_zunda.dat \
    vendor/sony/pdx237/proprietary/vendor/camera/SUN12BS1/lens_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SUN12BS1/lens_ctrl.dat \
    vendor/sony/pdx237/proprietary/vendor/camera/SUN12BS1/lens_ctrl_common.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SUN12BS1/lens_ctrl_common.dat \
    vendor/sony/pdx237/proprietary/vendor/camera/SUN12BS1/motion_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SUN12BS1/motion_detector.dat \
    vendor/sony/pdx237/proprietary/vendor/camera/SUN12BS1/motion_detector_sumomo.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SUN12BS1/motion_detector_sumomo.dat \
    vendor/sony/pdx237/proprietary/vendor/camera/SUN12BS1/motion_estimation.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SUN12BS1/motion_estimation.dat \
    vendor/sony/pdx237/proprietary/vendor/camera/SUN12BS1/object_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SUN12BS1/object_detector.dat \
    vendor/sony/pdx237/proprietary/vendor/camera/SUN12BS1/object_tracker.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SUN12BS1/object_tracker.dat \
    vendor/sony/pdx237/proprietary/vendor/camera/SUN12BS1/prc_image_conv.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SUN12BS1/prc_image_conv.dat \
    vendor/sony/pdx237/proprietary/vendor/camera/SUN12BS1/raw_conv_parisbrest.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SUN12BS1/raw_conv_parisbrest.dat \
    vendor/sony/pdx237/proprietary/vendor/camera/SUN12BS1/raw_proc_platform.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SUN12BS1/raw_proc_platform.dat \
    vendor/sony/pdx237/proprietary/vendor/camera/SUN12BS1/recognize_map_comp.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SUN12BS1/recognize_map_comp.dat \
    vendor/sony/pdx237/proprietary/vendor/camera/SUN12BS1/scene_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SUN12BS1/scene_detector.dat \
    vendor/sony/pdx237/proprietary/vendor/camera/default.dat:$(TARGET_COPY_OUT_VENDOR)/camera/default.dat \
    vendor/sony/pdx237/proprietary/vendor/camera/display_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/display_ctrl.dat \
    vendor/sony/pdx237/proprietary/vendor/camera/flash.dat:$(TARGET_COPY_OUT_VENDOR)/camera/flash.dat \
    vendor/sony/pdx237/proprietary/vendor/camera/optical_axis.dat:$(TARGET_COPY_OUT_VENDOR)/camera/optical_axis.dat \
    vendor/sony/pdx237/proprietary/vendor/camera/snapshot.dat:$(TARGET_COPY_OUT_VENDOR)/camera/snapshot.dat \
    vendor/sony/pdx237/proprietary/vendor/camera/streaming.dat:$(TARGET_COPY_OUT_VENDOR)/camera/streaming.dat \
    vendor/sony/pdx237/proprietary/vendor/camera/supported.dat:$(TARGET_COPY_OUT_VENDOR)/camera/supported.dat \
    vendor/sony/pdx237/proprietary/vendor/etc/acdbdata/kalama_qrd/Sony_acdb_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/kalama_qrd/Sony_acdb_cal.acdb \
    vendor/sony/pdx237/proprietary/vendor/etc/acdbdata/kalama_qrd/Sony_workspaceFileXml.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/kalama_qrd/Sony_workspaceFileXml.qwsp \
    vendor/sony/pdx237/proprietary/vendor/etc/audio/sku_kalama/mixer_paths_kalama_qrd.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio/sku_kalama/mixer_paths_kalama_qrd.xml \
    vendor/sony/pdx237/proprietary/vendor/etc/display/qdcm_calib_data_9.json:$(TARGET_COPY_OUT_VENDOR)/etc/display/qdcm_calib_data_9.json \
    vendor/sony/pdx237/proprietary/vendor/etc/displayconfig/display_port_131.xml:$(TARGET_COPY_OUT_VENDOR)/etc/displayconfig/display_port_131.xml \
    vendor/sony/pdx237/proprietary/vendor/etc/libhdr_somc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/libhdr_somc.xml \
    vendor/sony/pdx237/proprietary/vendor/etc/libnfc-nxp_RF.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nxp_RF.conf \
    vendor/sony/pdx237/proprietary/vendor/etc/sensors/config/kailua_ak991x_0_somc_product.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/kailua_ak991x_0_somc_product.json \
    vendor/sony/pdx237/proprietary/vendor/etc/zoom_noise_reduction/znr_Front_44k.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_Front_44k.tbl \
    vendor/sony/pdx237/proprietary/vendor/etc/zoom_noise_reduction/znr_Front_48k.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_Front_48k.tbl \
    vendor/sony/pdx237/proprietary/vendor/etc/zoom_noise_reduction/znr_Front_mono_44k.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_Front_mono_44k.tbl \
    vendor/sony/pdx237/proprietary/vendor/etc/zoom_noise_reduction/znr_Front_mono_48k.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_Front_mono_48k.tbl \
    vendor/sony/pdx237/proprietary/vendor/etc/zoom_noise_reduction/znr_Logical_44k.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_Logical_44k.tbl \
    vendor/sony/pdx237/proprietary/vendor/etc/zoom_noise_reduction/znr_Logical_48k.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_Logical_48k.tbl \
    vendor/sony/pdx237/proprietary/vendor/etc/zoom_noise_reduction/znr_Logical_mono_44k.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_Logical_mono_44k.tbl \
    vendor/sony/pdx237/proprietary/vendor/etc/zoom_noise_reduction/znr_Logical_mono_48k.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_Logical_mono_48k.tbl \
    vendor/sony/pdx237/proprietary/vendor/etc/zoom_noise_reduction/znr_P_UWide_44k.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_P_UWide_44k.tbl \
    vendor/sony/pdx237/proprietary/vendor/etc/zoom_noise_reduction/znr_P_UWide_48k.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_P_UWide_48k.tbl \
    vendor/sony/pdx237/proprietary/vendor/etc/zoom_noise_reduction/znr_P_UWide_mono_44k.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_P_UWide_mono_44k.tbl \
    vendor/sony/pdx237/proprietary/vendor/etc/zoom_noise_reduction/znr_P_UWide_mono_48k.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_P_UWide_mono_48k.tbl \
    vendor/sony/pdx237/proprietary/vendor/etc/zoom_noise_reduction/znr_P_Wide_44k.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_P_Wide_44k.tbl \
    vendor/sony/pdx237/proprietary/vendor/etc/zoom_noise_reduction/znr_P_Wide_48k.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_P_Wide_48k.tbl \
    vendor/sony/pdx237/proprietary/vendor/etc/zoom_noise_reduction/znr_P_Wide_mono_44k.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_P_Wide_mono_44k.tbl \
    vendor/sony/pdx237/proprietary/vendor/etc/zoom_noise_reduction/znr_P_Wide_mono_48k.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_P_Wide_mono_48k.tbl \
    vendor/sony/pdx237/proprietary/vendor/etc/zoom_noise_reduction/znr_default_44k.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_default_44k.tbl \
    vendor/sony/pdx237/proprietary/vendor/etc/zoom_noise_reduction/znr_default_48k.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_default_48k.tbl \
    vendor/sony/pdx237/proprietary/vendor/etc/zoom_noise_reduction/znr_parameter.xml:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_parameter.xml \
    vendor/sony/pdx237/proprietary/vendor/etc/zoom_noise_reduction/znr_parameter_back.xml:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_parameter_back.xml \
    vendor/sony/pdx237/proprietary/vendor/firmware/L-cs35l45-dsp1-spk-cali.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/L-cs35l45-dsp1-spk-cali.bin \
    vendor/sony/pdx237/proprietary/vendor/firmware/L-cs35l45-dsp1-spk-prot.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/L-cs35l45-dsp1-spk-prot.bin \
    vendor/sony/pdx237/proprietary/vendor/firmware/R-cs35l45-dsp1-spk-cali.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/R-cs35l45-dsp1-spk-cali.bin \
    vendor/sony/pdx237/proprietary/vendor/firmware/R-cs35l45-dsp1-spk-prot.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/R-cs35l45-dsp1-spk-prot.bin \
    vendor/sony/pdx237/proprietary/vendor/firmware/touch_module_id_0x02.img:$(TARGET_COPY_OUT_VENDOR)/firmware/touch_module_id_0x02.img \
    vendor/sony/pdx237/proprietary/vendor/lib64/camera/com.sony.sensormodule.crocus_kai_imx663.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.sony.sensormodule.crocus_kai_imx663.bin

PRODUCT_PACKAGES += \
    com.qti.eeprom.gt24p128c2csli_imx766 \
    com.qti.eeprom.gt24p64b_imx688 \
    com.qti.eeprom.irs2381c_polar \
    com.qti.eeprom.truly_cmb433 \
    com.qti.ois.bu63169gwz \
    com.qti.sensor.imx318 \
    com.qti.sensor.imx334 \
    com.qti.sensor.imx362 \
    com.qti.sensor.imx363 \
    com.qti.sensor.imx376 \
    com.qti.sensor.imx386 \
    com.qti.sensor.imx476 \
    com.qti.sensor.imx481 \
    com.qti.sensor.imx519 \
    com.qti.sensor.imx563 \
    com.qti.sensor.imx576 \
    com.qti.sensor.imx577 \
    com.qti.sensor.imx586 \
    com.qti.sensor.imx588 \
    com.qti.sensor.imx686 \
    com.qti.sensor.imx688 \
    com.qti.sensor.imx766 \
    com.qti.sensor.max7366_6dof \
    com.qti.sensor.max7366_eyetrack \
    com.qti.sensor.max7366_ov6211 \
    com.qti.sensor.max7366_ov9282 \
    com.qti.sensor.ov12a10 \
    com.qti.sensor.ov12a10_front \
    com.qti.sensor.ov13855 \
    com.qti.sensor.ov13880 \
    com.qti.sensor.ov64b40 \
    com.qti.sensor.ov7251 \
    com.qti.sensor.ov8856 \
    com.qti.sensor.ov8856_master \
    com.qti.sensor.ov8856_slave \
    com.qti.sensor.s5k2l7 \
    com.qti.sensor.s5k2x5sp \
    com.qti.sensor.s5k33dxx \
    com.qti.sensor.s5k3m5 \
    com.qti.sensor.s5k3p9 \
    com.qti.sensor.s5k4h7 \
    com.qti.sensor.s5k5e9yu05 \
    com.qti.sensor.s5k5e9yx04 \
    com.qti.sensor.s5khp1s \
    com.qti.sensor.s5kjd1sp \
    com.bots.node.vendortagwrite \
    com.qti.eisv2 \
    com.qti.eisv3 \
    com.qti.node.afbfusion \
    com.qti.node.aon \
    com.qti.node.customhwnode \
    com.qti.node.depth \
    com.qti.node.depthprovider \
    com.qti.node.dewarp \
    com.qti.node.dummydepth \
    com.qti.node.dummyrtb \
    com.qti.node.dummysat \
    com.qti.node.eisv2 \
    com.qti.node.eisv3 \
    com.qti.node.fcv \
    com.qti.node.formatconversion \
    com.qti.node.gme \
    com.qti.node.gpu \
    com.qti.node.gyrornn \
    com.qti.node.hdr10pgen \
    com.qti.node.hdr10phist \
    com.qti.node.memcpy \
    com.qti.node.ml \
    com.qti.node.muxer \
    com.qti.node.remosaic \
    com.qti.node.seg \
    com.qti.node.stich \
    com.qti.node.swaidenoiser \
    com.qti.node.swbestats \
    com.qti.node.swcac \
    com.qti.node.swec \
    com.qti.node.swfusion \
    com.qti.node.swhme \
    com.qti.node.swlsc \
    com.qti.node.swmctf \
    com.qti.node.swpdpc \
    com.qti.node.swpreprocess \
    com.qti.node.swregistration \
    com.qti.node.swvrt \
    com.qti.stats.aec \
    com.qti.stats.aecwrapper \
    com.qti.stats.aecxcore \
    com.qti.stats.af \
    com.qti.stats.afd \
    com.qti.stats.afwrapper \
    com.qti.stats.asd \
    com.qti.stats.awb \
    com.qti.stats.awbwrapper \
    com.qti.stats.cnndriver \
    com.qti.stats.haf \
    com.qti.stats.hafoverride \
    com.qti.stats.localhistogram \
    com.qti.stats.pdlib \
    com.qti.stats.pdlibsony \
    com.qti.stats.pdlibwrapper \
    com.qti.stats.statsgenerator \
    com.qti.stats.tracker \
    com.qtistatic.stats.aec \
    com.qtistatic.stats.af \
    com.qtistatic.stats.awb \
    com.qtistatic.stats.pdlib \
    libdepthmapwrapper_secure \
    libexcal_ckb_service_plugin \
    libexcal_color_ctrl_plugin \
    libexcal_debug_display_plugin \
    libexcal_draw_comp_plugin \
    libexcal_dual_bokeh_comp_plugin \
    libexcal_exposure_analyzer_plugin \
    libexcal_exposure_ctrl_plugin \
    libexcal_eye_stabilizer_plugin \
    libexcal_face_detector_plugin \
    libexcal_flicker_detector_plugin \
    libexcal_food_comp_plugin \
    libexcal_hal_ctrl_plugin \
    libexcal_hdr_plugin \
    libexcal_idt_ctrl_plugin \
    libexcal_image_conv_plugin \
    libexcal_iq_ctrl_plugin \
    libexcal_jpeg_enc_plugin \
    libexcal_lens_ctrl_plugin \
    libexcal_motion_detector_plugin \
    libexcal_motion_estimation_plugin \
    libexcal_object_detector_plugin \
    libexcal_object_tracker_plugin \
    libexcal_offline_process_ctrl_plugin \
    libexcal_prc_image_conv_plugin \
    libexcal_raw_conv_plugin \
    libexcal_raw_dump_plugin \
    libexcal_raw_proc_plugin \
    libexcal_recognize_map_comp_plugin \
    libexcal_req_ctrl_plugin \
    libexcal_scene_detector_plugin \
    libexcal_single_bokeh_comp_plugin \
    libexcal_snapshot_ctrl_plugin \
    libexcal_splitter_plugin \
    libexcal_stream_ctrl_plugin \
    com.qti.camx.chiiqutils \
    com.qti.chiusecaseselector \
    com.qti.feature2.afbrckt \
    com.qti.feature2.anchorsync \
    com.qti.feature2.demux \
    com.qti.feature2.derivedoffline \
    com.qti.feature2.frameselect \
    com.qti.feature2.fusion \
    com.qti.feature2.generic \
    com.qti.feature2.gs.sm8550 \
    com.qti.feature2.hdr \
    com.qti.feature2.mcreprocrt \
    com.qti.feature2.memcpy \
    com.qti.feature2.mfsr \
    com.qti.feature2.ml \
    com.qti.feature2.mux \
    com.qti.feature2.qcfa \
    com.qti.feature2.rawhdr \
    com.qti.feature2.realtimeserializer \
    com.qti.feature2.rt \
    com.qti.feature2.rtmcx \
    com.qti.feature2.serializer \
    com.qti.feature2.statsregeneration \
    com.qti.feature2.stub \
    com.qti.feature2.swmf \
    com.qti.qseeaon \
    com.qti.qseeutils \
    com.qti.settings.sm8550 \
    com.qti.stats.common \
    com.qualcomm.mcx.distortionmapper \
    com.qualcomm.mcx.linearmapper \
    com.qualcomm.mcx.nonlinearmapper \
    com.qualcomm.mcx.policy.mfl \
    com.qualcomm.mcx.policy.xr \
    com.qualcomm.qti.mcx.usecase.extension \
    camera.qcom \
    com.qti.chi.offline \
    com.qti.chi.override \
    libaidenoiser \
    libaidenoiserv2 \
    libarcsoft_bokeh_adapter \
    libbitmlengine \
    libbitmlenginev2 \
    libcamerapostproc \
    libcammw \
    libcamxcommonutils \
    libcamxexternalformatutils \
    libcamxfdengine \
    libcamxhwnodecontext \
    libcamxifestriping \
    libcamximageformatutils \
    libcamxqsatalgo \
    libcamxsettingsmanager \
    libcamxstatscore \
    libcamxswispiqmodule \
    libcamxswprocessalgo \
    libcamxtintlessalgo \
    libchifeature2 \
    libcom.qti.chinodeutils \
    libcommonchiutils \
    libexcal_core \
    libexcal_system \
    libhdr10plus \
    libipebpsstriping \
    libipebpsstriping170 \
    libipebpsstriping480 \
    libisphwsetting \
    libjpege \
    libmctfengine_stub \
    libmfec \
    libmmcamera_bestats \
    libmmcamera_cac3 \
    libmmcamera_lscv35 \
    libmmcamera_mfnr \
    libmmcamera_mfnr_t4 \
    libmmcamera_pdpc \
    libopencv \
    libopestriping \
    libqll \
    libqll10 \
    libqllengine \
    libqsegnet \
    libsomc_buttercake \
    libsomc_camerahal \
    libsomc_cheesescone \
    libsomc_chokoballcmn \
    libsomc_chokoballpal \
    libsomc_drops \
    libsomc_formatconverter \
    libsomc_histogram \
    libsomc_marble \
    libsomc_parisbrest \
    libsomc_pocky \
    libsomc_pretzchoco \
    libsomc_raisincl \
    libsomc_shortcake \
    libsomc_sumomo \
    libsomc_yummy \
    libtfestriping \
    libubifocus \
    libvideoml \
    local_libcamera_metadata \
    vendor.qti.hardware.camera.aon-service-impl \
    vendor.qti.hardware.camera.postproc@1.0-service-impl \
    vendor.somc.camera.device-impl \
    vendor.somc.hardware.camera.provider@1.0-service
